#Comment to push fresh commit
version: 2.0
jobs:
  build:
    working_directory: ~/vault-circleci-auth-plugin
    docker:
      - image: marcboudreau/golang-docker-git-circleci:latest
    steps:
      - checkout
      - setup_remote_docker
#      - run:
#          name: Build All Platforms
#          command: |
#            work_dir=/usr/local/go/src/github.com/marcboudreau/vault-circleci-auth-plugin
#            container_id="brian_test"
#            docker start -a $container_id
#            docker rm -f $container_id
      - run:
          name: Building Docker Image
          command: |
            docker build -t vault-circleci-auth-plugin:test .
      - run:
          name: Running Tests
          command: ./integration-test/tests.sh
      - run:
          name: Release
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              RELEASE=$$CIRCLE_SHA1 

              docker tag vault-circleci-auth-plugin:test brianoh1979/vault-circleci-auth-plugin:$RELEASE
              docker tag vault-circleci-auth-plugin:test brianoh1979/vault-circleci-auth-plugin:latest

              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
              docker push brianoh1979/vault-circleci-auth-plugin
            fi
